### ISSUE TITLE
Regression: Firefox no longer prints structures in 1.0.7

### ISSUE THREAD

**Issue by rome-user** [binaryage/cljs-devtools#75] opened 2023-05-02 23:25 UTC
When using `[binaryage/devtools "1.0.6"]`, I can see CLJS maps printed in Firefox's browser console, but when I upgrade to `[binaryage/devtools "1.0.7"]`, I no longer see the custom formatters on Firefox 113 beta.

Here is a demonstration using `lambdaisland.glogi` as my logger. I am running the following code in CLJS REPL.
```clojure
cljs.user> (lambdaisland.glogi/info :message "Test")
nil
cljs.user> (lambdaisland.glogi/info :foo "bar" :baz "quux")
nil
```

*1.0.6 Screenshot*
<img width="326" alt="1.0.6 Screenshot" src="https://user-images.githubusercontent.com/114131048/235806057-22037c76-0ae1-45ac-a8e7-6e7a5eb8ccb0.png">

*1.0.7 Screenshot*
<img width="1129" alt="1.0.7 Screenshot" src="https://user-images.githubusercontent.com/114131048/235806075-b2225bc1-c6d2-4cd6-b0df-fd807ef67e5d.png">

**Comment by nchevobbe** [comment] 2023-05-24 15:07
From the screenshot, it looks like custom formatters are not enabled
Can you double check in `about:config` that both `devtools.custom-formatters` and `devtools.custom-formatters.enabled` are set to true (and restart devtools if they weren't before checking if it works)

**Comment by rome-user** [comment] 2023-05-25 04:05
That seems to have fixed the issue. I guess Firefox defaults changed? But now the colors seem to be off compared to 1.0.6. Here is a screenshot of 1.0.7. with both `devtools.custom-formatters` and `devtools.custom-formatters.enabled` set to `true`.

![1 0 7 logging](https://github.com/binaryage/cljs-devtools/assets/114131048/4e020307-39c7-49cf-8d04-41dc66fb809d)

**Comment by SebastianZ** [comment] 2023-05-25 09:22
> I guess Firefox defaults changed?

No, they are still `false` by default. Though `devtools.custom-formatters` will be removed soon and `devtools.custom-formatters.enabled` can then be enabled via the option "Enabled custom formatters" in the Settings panel like in Chrome.

> But now the colors seem to be off compared to 1.0.6

Hmm, I didn't make any color changes for Firefox. How are 1.0.6 and 1.0.7 displayed for you in Chrome?

Sebastian

**Comment by rome-user** [comment] 2023-05-28 09:51
In Chrome they appear the same. For some reason only Firefox was able to display "appropriate" colors for dark mode.
<img src="https://github.com/binaryage/cljs-devtools/assets/114131048/b4222294-9363-436a-b4ba-6cf27a98053b">

**Comment by SebastianZ** [comment] 2023-05-31 14:34
[1.0.7](https://github.com/binaryage/cljs-devtools/releases/tag/v1.0.7) is the first version that actually supports Firefox.
And as the display is the same in Firefox and Chrome with 1.0.7 and there's no difference between 1.0.6 and 1.0.7 in Chrome, it seems this is rather an issue related to missing a dark mode.
And that's covered in #30.

So I'm going to close this issue as a duplicate of the other one.

Sebastian

**Closed as completed** 2023-05-31 14:34 UTC
