### ISSUE TITLE
How about electron?

### ISSUE THREAD

**Issue by jiyinyiyong** [binaryage/cljs-devtools#13] opened 2016-03-15 06:46 UTC
To debug Node.js programs people invented node-inspector and devtool to use Chrome DevTools in Node.js and it looks good. I tried but `cljs-devtools` is not able to run inside devtool. Any solution yet?

https://github.com/Jam3/devtool

**Comment by darwin** [comment] 2016-03-15 13:45
I developed an [Electron-based app](https://github.com/darwin/plastic) and cljs-devtools worked for me using internal Electron devtools.

On the other hand, using pure node.js environment with devtools cannot use custom formatters, because there is no "window" object, like in the browser context. This cannot be fixed on cljs-devtools side, the problem is a shortcoming of the custom formatters specification in Chrome.

See:
https://docs.google.com/document/d/1FTascZXT9cxfetuPRT2eXPQKXui4nWFivUnS_335T3U/edit#heading=h.xuvxhsd2bp05

**Closed** 2016-03-21 00:42 UTC

**Comment by jiyinyiyong** [comment] 2016-03-30 04:34
In my case I use ClojureScript on both browser side and server side, and debugging Node.js is quite hard since the DevTools is not as nice as that in a browser. I use mainly two tools, devtool(the link above) and node-inspector. It seems both of them does not support this custom formatter. Do you have any ideas on fixing that?

**Comment by darwin** [comment] 2016-03-30 10:41
As I wrote, custom formatters are supported only in Chrome DevTools.

Support for other environments is probably possible but it would require forking devtool or node-inspector to support it somehow. Or alternatively you could re-implement console as a plain HTML app and use your own logging protocol to display values (and leverage cljs-devtools by "emulating" custom formatters). Something along the lines of this proposal: https://github.com/binaryage/cljs-devtools/issues/11
