### ISSUE TITLE
Support for IPrintWithWriter on raw JS types

### ISSUE THREAD

**Issue by vikeri** [binaryage/cljs-devtools#21] opened 2016-06-30 07:51 UTC
I have implemented custom writers for goog.date.Date using `IPrintWithWriter`. The `#gdate` shows correctly but the actual parsed object does not show as it is supposed to. In the REPL it shows `#gdate [2016 5 29]` but in cljs-devtools it shows `#gdate [object Object]`. Is this working for others?

**Comment by darwin** [comment] 2016-06-30 20:16
AFAIK `IPrintWithWriter` should be properly supported by cljs-devtools.

**Comment by danielcompton** [comment] 2016-07-01 07:31
Can you share you writers? We have custom writers which showup fine in devtools.

```
(extend-protocol IPrintWithWriter
  goog.date.DateTime
  (-pr-writer [goog-date writer _]
    (write-all writer "#date \"" (.getTime goog-date) "\"")))

(defn- utc->DateTime [ms]
  (doto (goog.date.DateTime.) (.setTime ms)))

(cljs.reader/register-tag-parser! "date" utc->DateTime)


(extend-protocol IPrintWithWriter
  goog.date.UtcDateTime
  (-pr-writer [goog-date writer _]
    (write-all writer "#utc \"" (.getTime goog-date) "\"")))

(defn- utc->UtcDateTime [ms]
  (doto (goog.date.UtcDateTime.) (.setTime ms)))

(cljs.reader/register-tag-parser! "utc" utc->UtcDateTime)
```

**Comment by vikeri** [comment] 2016-07-01 07:33
@danielcompton, @darwin 
Might be React Native related then. My writer is the following:
```
 (extend-protocol IPrintWithWriter
    Date
    (-pr-writer [obj writer _opts]
      (write-all writer
                 "#gdate "
                 [(.getYear obj)
                  (.getMonth obj)
                  (.getDate obj)]))
```

**Comment by darwin** [comment] 2016-07-03 10:45
If you provide a small repo with repro case (normal lein or boot project without react native), I will look into that.

btw. The snippet looks good at first glance, don't know where it the "Date" thing coming from.

**Comment by vikeri** [comment] 2016-07-04 07:43
Here is an example repo: https://github.com/vikeri/mwe-cljs-devtools/blob/master/src/mwe/ios/core.cljs

**Comment by darwin** [comment] 2016-07-04 09:32
Thank you for example repo, but I'm not going to dig into that any further. I have never done any react native work (and react native CLJS tooling ads another complex layer of tooling on top of it). Just spent 30 minutes trying to make it work and I failed[1]. I'm using the simulator, followed the steps in the readme with a bit of googling how to install react-native and re-natal.

Here are my observations so far:
1. println cannot work as you expect with cljs-devtools (assuming this[2] is the way how you enable console printing). See my explanation here[3].
2. when I dismiss figwheel and websocket errors I can see a warning from cljs-devtools[4] that custom formatters were not installed (which is expected, because iPhone runs on webkit and CFs are supported only under Chrome and try to detect that[5]).
3. I tried to follow this[5] article to poke around, but I was unable to make DevTools attach to my simulator instance. Packager prints "Launching Dev Tools..." into terminal, new browser tab opens, but then it just halts and simulator shows another red screen of death.

I'm sorry I cannot invest time into this unless you provide a simple repro case without all the extra tooling. Even figwheel is unnecessary complication, we don't need it in minimal repro case.
Also I'm wondering that cljs-devtools work at all with attached chrome devtools to webkit-based javascript engine. Or am I missing something? Do you browse the app in chrome directly somehow?

[1] https://dl.dropboxusercontent.com/u/559047/mwe-problem-1.png
[2] https://github.com/vikeri/mwe-cljs-devtools/blob/master/env/dev/env/ios/main.cljs#L10
[3] https://github.com/binaryage/cljs-devtools/issues/5#issuecomment-132212643
[4] https://dl.dropboxusercontent.com/u/559047/mwe-problem-2.png
[5] https://medium.com/@shaheenghiassy/deep-diving-react-native-debugging-ea406ed3a691#.eprw85awc

**Comment by darwin** [comment] 2016-07-04 10:08
Good news I was able to reproduce your behaviour in cljs-devtools-sample project[1].
It looks like you described[2].

![](https://dl.dropboxusercontent.com/u/559047/cljs-devtools-issue21-repro.png)

Explanation for println behaviour is same like in my previous post. Println turns all params into strings via pr-str and then passes them into console, so there is nothing much cljs-devtools can do about it.

The explanation for `(.log js/console (goog.date.Date.))` is also simple. `goog.date.Date` is a javascript "type", it is not marked as coming from clojurescript. That is why cljs-devtools do not try to format it and leave the presentation to default console behaviour.If you want to go through cljs printing machinery, you could write something like this: `(.log js/console (pr-str (goog.date.Date.)))`

As of the first log line. It properly detects the we are printing cljs map, which is a proper cljs type so it is going through custom formatters. But it fails to properly print it via IPrintWithWriter. Not sure why. I'm going to look into that.



[1] https://github.com/binaryage/cljs-devtools-sample/commit/62aecae5f9db2c2c79f0e0152043f5aceea126f7
[2] https://dl.dropboxusercontent.com/u/559047/cljs-devtools-issue21-repro.png

**Comment by vikeri** [comment] 2016-07-04 10:23
I am very sorry I had you to dig around in React Native. It is quite a mess to get everything working properly in React Native.

It is not a huge issue so I'm very humbled by the effort you put into it. Great that you have triangulated the issue however. Tell me if there is anything I could do to help! Great work on `cljs-devtools` btw! Incredibly useful!

**Closed** 2016-07-06 12:27 UTC

**Comment by vikeri** [comment] 2016-07-06 12:37
🎉
