### ISSUE TITLE
Make :async feature awesome

### ISSUE THREAD

**Issue by darwin** [binaryage/cljs-devtools#20] opened 2016-06-22 23:22 UTC
This is a placeholder issue for people who want to track the progress of this experimental feature.

The announcement from Slack:

> Hi, just wanted to share with you a half-baked idea which enables long stack traces for core.async in ClojureScript:
> You can get this[1] instead of this[2]:
> [1] https://dl.dropboxusercontent.com/u/559047/core-async-long-stack-traces.png 
> [2] https://dl.dropboxusercontent.com/u/559047/core-async-normal-traces.png
> The trick is to replace goog.async.nextTick with a promise-based implementation. ES6 promises participate in Chrome DevTools “async” feature. it is not super useful ATM, because maxAsyncStackChainDepth is currently hard-coded in DevTools and set to only 4, which is not enough for more complex core.async code:
> https://github.com/binaryage/dirac/blob/devtools/front_end/sdk/DebuggerModel.js#L200
> but in Dirac I can lift that number and maybe walk the call stack in a better way, so loops won’t create long stack traces
> 
> here is the implementation if anyone interested: https://github.com/binaryage/cljs-devtools/commit/86dbbbbeca5725547ead2f7b852743a7176413f7
> 
> here is an upstream proposal how to handle long async-task chains generated by core.async:
> https://bugs.chromium.org/p/chromium/issues/detail?id=622506

**Comment by danielcompton** [comment] 2016-10-31 19:46
We ran into an obscure bug because of the `:async` feature. The nut of the issue is that the `:async` feature swaps goog.nextTick which schedules tasks, for a promise based mechanism which schedules microtasks. For interested readers, see [Tasks, microtasks, queues, and schedules](https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/) for more info on tasks and microtasks.

We were trying to schedule CPU intensive work to occur after an animation frame (task) had finished. goog.nextTick schedules a task to run after the frame has finished (and rendered), but the promise based implementation scheduled the work as a microtask. The microtask runs in the same task as the animation frame, therefore delaying rendering of the animation frame until the CPU intensive work has finished.

The docstring for nexttick says:

> Fires the provided callbacks as soon as possible after the current JS execution context. setTimeout(…, 0) takes at least 4ms when called from within another setTimeout(…, 0) for legacy reasons.
> **This will not schedule the callback as a microtask** (i.e. a task that can preempt user input or networking callbacks). It is meant to emulate what setTimeout(_, 0) would do if it were not throttled. If you desire microtask behavior, use {@see goog.Promise} instead.

I know that `:async` is experimental, but I wonder if a promise-based approach is sound, as it can subtly and confusingly change the behaviour of an app? Alternatively, should the `:async` monkeypatch be more tightly scoped to affect the behaviour of core.async go loops, and not other code which calls nexttick directly?

**Comment by mike-thompson-day8** [comment] 2016-10-31 20:31
Just to add to what @danielcompton reported ...  the development version of our app showed a bug (because it was using the patched `goog.next.tick`) whereas the production build did not.  Which was utterly baffling.  It took some luck and a lot of time looking at Chrome devtools flame charts to figure it out.

But in some sense we were lucky. If this patch was masking a bug (instead of causing one), that would have been worse because you have no chance of debugging optimised code. 

I would suggest that this `:async` feature should be, by default, turned off. Then someone can choose to explicitly turn it on, after having read the implications.

**Comment by darwin** [comment] 2016-10-31 20:54
I'm sorry to hear about the problems it caused. Thanks for sharing your experience.

> Alternatively, should the :async monkeypatch be more tightly scoped to affect the behaviour of core.async go loops, and not other code which calls nexttick directly?

This :async thing should be general, not only core.async specific. So I wanted to apply it globally. Also people could run into these timing issues with core.async alone.

Do you think a fix for this issue would be to use original `goog.nextTick` inside my promise? So I would resolve the promise after waiting for next tick internally. This way we would get original timing profile, but still devtools would display async callstack chain.

**Comment by danielcompton** [comment] 2016-10-31 21:41
> Do you think a fix for this issue would be to use original goog.nextTick inside my promise? So I would resolve the promise after waiting for next tick internally. This way we would get original timing profile, but still devtools would display async callstack chain.

That sounds possible. We can test that against our internal app to see if that fixes the problem. My understanding of how it would work would be:

1. run nexttick
2. create a promise
3. schedule the promise to be resolved with the real nexttick
4. nexttick fires, promise is resolved, scheduling a microtask
5. JS VM runs outstanding microtasks, executing the promise's "then" function

As long as the promise was resolved in a separate task (triggered by the original nexttick), I think that should work. However, I'm still a little bit cautious about this feature for re-frame apps, as it is quite sensitive to the behaviour of the JS task queue.

**Comment by darwin** [comment] 2016-10-31 21:57
I tried a few experiments and I cannot make it to work.

As soon as I introduce `goog.async.nextTick.getSetImmediateEmulator_` as a waiting step to get proper timing the devtools loses track of that "thread" of async calls.

**Comment by darwin** [comment] 2016-10-31 22:00
I think we will have to wait for chrome devs to add proper support for postMessage/onmessage and treat them as async operations. At that point this `:async` hack won't be necessary anymore.

https://github.com/google/closure-library/blob/fd043939bde2de4cd0dae9272e3336fbc5f66962/closure/goog/async/nexttick.js#L217

**Comment by darwin** [comment] 2016-10-31 22:12
relevant issues in Chromium:
https://bugs.chromium.org/p/chromium/issues/detail?id=272416
https://bugs.chromium.org/p/chromium/issues/detail?id=332624

**Comment by danielcompton** [comment] 2016-11-01 00:46
Thanks for your detailed investigation on this :) I'll follow those chrome bugs.

**Comment by darwin** [comment] 2016-11-02 19:24
Tracked as a new chromium issue here:
https://bugs.chromium.org/p/chromium/issues/detail?id=661705

**Comment by darwin** [comment] 2018-01-13 15:42
FYI: upstream issue was fixed, the :async feature will be removed from cljs-devtools eventually

https://bugs.chromium.org/p/chromium/issues/detail?id=661705

**Closed** 2018-01-14 23:04 UTC
Labels: chrome-bug

**Comment by dijonkitchen** [comment] 2018-11-08 00:43
Should the `:async` feature be removed along with the console.log since most people are on Chrome 65+ now? https://caniuse.com/usage-table

**Comment by darwin** [comment] 2018-11-08 17:14
The `:async` feature is disabled by default. I don't see any harm leaving it there as is. Removing it could force some people who have it enabled to revisit this issue or maybe silently affect behaviour of their code.
